title: "GRACE-GRACE-FO-TWS"
description: "Global Total Water Storage (TWS) data derived from GRACE and GRACE-FO satellite missions. This dataset is used for hydrological and climate monitoring, assessing water resources on a global scale."

recipes:
  - id: "GRACE-GRACE-FO-TWS"
    object: "recipe:GRACE-GRACE-FO-TWS"

provenance:
  providers:
    - name: "NASA GRACE & GRACE-FO Mission"
      description: "NASA's GRACE and GRACE-FO missions measure changes in Earth's water storage, using satellite gravimetry data to monitor total water storage variations worldwide."
      roles:
        - data provider
        - research institution
      url: "https://www.nasa.gov/mission_pages/grace/index.html"

    - name: "Jet Propulsion Laboratory (JPL)"
      description: "The Jet Propulsion Laboratory (JPL) processes GRACE and GRACE-FO satellite data for Earth science research and water storage monitoring."
      roles:
        - data provider
        - research institution
      url: "https://www.jpl.nasa.gov/"

  license: "Creative Commons Attribution 4.0 (CC BY 4.0)"

acknowledgements: >
  The GRACE and GRACE-FO Total Water Storage dataset is based on data from NASA's GRACE and GRACE-FO missions, which measure Earth's gravity field variations to monitor changes in global water storage. We acknowledge the **NASA GRACE and GRACE-FO mission teams** for providing the satellite gravimetry data, which is accessible at [NASA GRACE page](https://www.nasa.gov/mission_pages/grace/index.html). The dataset has been validated through comparisons with hydrological models, in-situ measurements, and other water resources monitoring efforts.

citation:
  - authors: "Landerer, F.W., Swenson, S.C."
    year: 2012
    title: "Accuracy of scaled GRACE terrestrial water storage estimates."
    journal: "Water Resources Research"
    volume: 48
    pages: W04531
    doi: "10.1029/2011WR011453"

  - authors: "Wahr, J., Molenaar, M., & Bryan, F."
    year: 1998
    title: "Time-variable gravity from satellite observations."
    journal: "Journal of Geophysical Research"
    volume: 103
    pages: 30205-30229
    doi: "10.1029/98JB02844"

contact:
  email: "grace@nasa.gov"

maintainers:
  - name: "Mitra Cattry"
    github: "mitraA90"
  - name: "Raphael Hagen"
    github: "norlandrhagen"
